spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/blue
    username: blue
    password: blue123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: false

server:
  port: 8080

security:
  jwt:
    secret: 8QhlObv+ET15Oi5Jr1NHxiEl6ToJLBb45a0EDuTtIUE=
    expirationMillis: 86400000
