spring:
  application:
    name: blue-api

  profiles:
    active: dev

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/blue}
    username: ${DB_USERNAME:blue}
    password: ${DB_PASSWORD:blue123}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: false

server:
  port: ${SERVER_PORT:8080}

security:
  jwt:
    secret: ${JWT_SECRET:8QhlObv+ET15Oi5Jr1NHxiEl6ToJLBb45a0EDuTtIUE=}
    expirationMillis: ${JWT_EXPIRATION_MS:86400000}
