spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/blue
    username: blue
    password: blue123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update         # conveniente no dev
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: true         # ok no dev, cuidado em prod

  flyway:
    enabled: false             # liga quando tiver migrations

# Se quiser logs mais verbosos no dev:
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
