spring:
  application:
    name: blue-api

  # Perfil padrão caso não especifique via env (-Dspring.profiles.active=prod)
  profiles:
    default: dev

server:
  port: ${SERVER_PORT:8080}

security:
  jwt:
    # Em produção, injete por variável de ambiente (não commitar segredo!)
    secret: ${JWT_SECRET:8QhlObv+ET15Oi5Jr1NHxiEl6ToJLBb45a0EDuTtIUE=}
    expirationMillis: ${JWT_EXPIRATION_MILLIS:86400000}

# Swagger/OpenAPI: ligado por padrão; no prod desligamos abaixo
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
