spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/blue
    username: blue
    password: blue123
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
server:
  port: 8080
