spring:
  datasource:
    url: ${DB_URL}             # ex: jdbc:postgresql://db-host:5432/blue
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none           # NUNCA usar update/create em produção
    show-sql: false
    properties:
      hibernate:
        format_sql: false
    open-in-view: false        # evita N+1/exposição de sessão no prod

  flyway:
    enabled: true              # recomenda-se migrations em prod
    locations: classpath:db/migration
    baseline-on-migrate: true  # útil se já houver tabelas pré-existentes

server:
  port: ${SERVER_PORT:8080}
  compression:
    enabled: true
    min-response-size: 1024

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

logging:
  level:
    root: INFO
    org.springframework.web: WARN
    org.hibernate: WARN
